# Generated by Django 5.1.15 on 2026-07-23 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0003_project'),
        ('eln', '0002_initial'),
        ('helix_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('prefix', models.CharField(help_text='Uppercase letters, e.g. BLOOD. Used to generate display IDs like BLOOD1.', max_length=20, unique=True)),
                ('columns', models.JSONField(blank=True, default=list, help_text='Ordered array of column definitions: {id, name, type, required, default, units, description}.')),
                ('icon', models.CharField(default='🧪', help_text='Single emoji used as the icon for this entity type in reference badges.', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Soft-delete flag. Inactive schemas are hidden from dropdowns but preserve existing entities.')),
                ('content_hash', models.CharField(blank=True, default='', help_text='SHA-256 hash of column definitions (id, name, type, required, default, units). Computed on every save.', max_length=64)),
            ],
            options={
                'db_table': 'lims_entity_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_id', models.CharField(editable=False, max_length=50, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('finished', 'Finished')], default='in_progress', max_length=20)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.folder')),
                ('last_editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, help_text='Placeholder FK — the Project model is not yet implemented.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.project')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='helix_core.schema')),
                ('source_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lims_entities', to='eln.notebookentry')),
            ],
            options={
                'verbose_name_plural': 'entities',
                'db_table': 'lims_entity',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=100)),
                ('target_type', models.CharField(help_text="Namespaced target type, e.g. 'eln.entry' or 'lims.entity'.", max_length=100)),
                ('target_id', models.IntegerField(help_text='PK of the target record.')),
                ('request_id', models.UUIDField(blank=True, help_text='Correlation ID tying together action rows from the same HTTP request.', null=True)),
                ('client_ip', models.GenericIPAddressField(blank=True, help_text='Client IP auto-captured from the request.', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actions', to=settings.AUTH_USER_MODEL)),
                ('source_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='eln.notebookentry')),
                ('version', models.ForeignKey(blank=True, help_text='Content version produced by this action. Null for non-versioned targets.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='eln.contentversion')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='lims.entity')),
            ],
            options={
                'db_table': 'lims_action',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegisteredEntityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(help_text="Uppercase letters extracted from display IDs, e.g. 'E', 'DNA'. Must be unique across all entity types.", max_length=20, unique=True)),
                ('workspace_id', models.CharField(help_text='The workspace that owns this entity type. Used as the URL namespace: /{workspaceId}/{displayId}.', max_length=100)),
                ('display_name', models.CharField(help_text="Human-readable name shown in search results, e.g. 'Entry', 'DNA Sequence'.", max_length=255)),
                ('content_type', models.ForeignKey(help_text='The Django model that backs entities with this prefix.', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'lims_registered_entity_type',
                'ordering': ['prefix'],
            },
        ),
    ]
