# Generated by Django 5.1.15 on 2026-07-23 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LimsView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('filter_state', models.JSONField(blank=True, default=dict, help_text='Structured filter state equivalent to URL params: { search, schema_type, schema, status, sort, fields, columns, viewMode }')),
                ('is_public', models.BooleanField(default=False, help_text='When True, the View appears in the Global Views sidebar for all users.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lims_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lims_view',
                'ordering': ['-updated_at'],
            },
        ),
    ]
