# Generated by Django 5.1.15 on 2026-07-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0002_backfill_registered_entity_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitytype',
            name='content_hash',
            field=models.CharField(blank=True, default='', help_text='SHA-256 hash of column definitions (id, name, type, required, default, units). Computed on every save.', max_length=64),
        ),
        migrations.AlterField(
            model_name='entitytype',
            name='columns',
            field=models.JSONField(blank=True, default=list, help_text='Ordered array of column definitions: {id, name, type, required, default, units, description}.'),
        ),
    ]
