# Generated by Django 5.1.15 on 2026-08-02 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0005_alter_entity_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='lims.entity'),
        ),
    ]
