# Generated by Django 5.1.15 on 2026-08-02 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0006_alter_action_entity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('aggregate_function', models.CharField(help_text='Aggregate ID from the column type registry: count, count_distinct, sum, avg, min, max, stdev.', max_length=50)),
                ('column', models.CharField(blank=True, help_text='Column key to aggregate over.  None/empty for a plain row count (counts rows without a column target).', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lims_metrics', to=settings.AUTH_USER_MODEL)),
                ('view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='lims.limsview')),
            ],
            options={
                'db_table': 'lims_metric',
                'ordering': ['-updated_at'],
            },
        ),
    ]
