# Generated by Django 5.1.15 on 2026-08-27 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0012_dangling_source_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='source_entry',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='folder',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='source_entry',
        ),
    ]
