# Generated by Django 5.1.15 on 2026-07-03 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0003_allow_blank_pin_label"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="PinnedWorkspace",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("display_id", models.CharField(max_length=255)),
                        ("label", models.CharField(blank=True, default="", max_length=255)),
                        ("url", models.CharField(max_length=500)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="pinned_workspaces", to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        "db_table": "core_pinned_workspace",
                        "ordering": ["-created_at"],
                        "unique_together": {("user", "url")},
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
