# Generated by Django 5.1.15 on 2026-07-25 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eln', '0004_alter_elnaction_action_alter_elnaction_action_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dropdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('options', models.JSONField(blank=True, default=list, help_text='Ordered array of option-value strings.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dropdowns_dropdown',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DropdownsAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text="Triple-dotted action identifier, e.g. 'eln.entry.created'.", max_length=128)),
                ('action_type', models.CharField(help_text="Core CRUD verb: 'created', 'edited', or 'deleted'.", max_length=16)),
                ('target_type', models.CharField(help_text="Namespaced target type, e.g. 'eln.entry' or 'lims.entity'.", max_length=100)),
                ('target_id', models.IntegerField(help_text='PK of the target record.')),
                ('request_id', models.UUIDField(blank=True, help_text='Correlation ID tying together action rows from the same HTTP request.', null=True)),
                ('client_ip', models.GenericIPAddressField(blank=True, help_text='Client IP auto-captured from the request.', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actions', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(blank=True, help_text='Content version produced by this action. Null for non-versioned targets.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='eln.contentversion')),
            ],
            options={
                'verbose_name': 'Dropdowns action',
                'verbose_name_plural': 'Dropdowns actions',
                'db_table': 'dropdowns_action',
            },
        ),
    ]
