# Generated by Django 5.1.15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("access", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_key', models.CharField(blank=True, default='', max_length=100)),
                ('color_key', models.CharField(blank=True, default='', max_length=100)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='team', to='auth.group')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='access.organization')),
            ],
            options={
                'db_table': 'access_team',
            },
        ),
    ]
