# Generated by Django 5.1.15 on 2026-06-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eln', '0003_alter_notebookentry_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebookentry',
            name='display_id',
            field=models.CharField(editable=False, max_length=20, null=True, unique=True),
        ),
    ]
