# Generated by Django 5.1.15 on 2026-06-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eln', '0006_make_entry_folder_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebookentry',
            name='display_id',
            field=models.CharField(editable=False, max_length=50, null=True, unique=True),
        ),
    ]
