# Generated by Django 5.1.15 on 2026-07-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eln', '0007_alter_notebookentry_display_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebookentry',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('finished', 'Finished')], default='in_progress', max_length=20),
        ),
    ]
