# Generated by Django 5.1.15 on 2026-07-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eln', '0008_notebookentry_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(choices=[('enzyme', 'Enzyme'), ('flask', 'Flask'), ('solvent', 'Solvent'), ('warn', 'Warn'), ('primary', 'Primary'), ('success', 'Success'), ('destructive', 'Destructive'), ('muted', 'Muted')], default='primary', max_length=50)),
                ('entries', models.ManyToManyField(related_name='tags', to='eln.notebookentry')),
            ],
            options={
                'db_table': 'eln_tag',
                'ordering': ['name'],
            },
        ),
    ]
