# Generated by Django 5.1.15 on 2026-07-09 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='Mention',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('source_id', models.PositiveIntegerField()),
                        ('target_id', models.PositiveIntegerField()),
                        ('source_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mention_sources', to='contenttypes.contenttype')),
                        ('target_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                    ],
                    options={
                        'db_table': 'eln_mention',
                    },
                ),
            ],
        ),
    ]
