# Generated by Django 5.1.15 on 2026-06-24

from django.db import migrations, models

EMPTY_DOC = '{"type": "doc", "content": [{"type": "paragraph"}]}'


def wrap_text_in_tiptap_doc(text):
    """Wrap plain text in a TipTap paragraph node, returning a JSON string."""
    if not text:
        return EMPTY_DOC
    import json

    doc = {
        "type": "doc",
        "content": [
            {
                "type": "paragraph",
                "content": [{"type": "text", "text": text}],
            }
        ],
    }
    return json.dumps(doc)


def convert_existing_content(apps, schema_editor):
    """Convert existing plain-text content to valid TipTap JSON documents."""
    NotebookEntry = apps.get_model("eln", "NotebookEntry")
    for entry in NotebookEntry.objects.only("id", "content").iterator():
        if entry.content and isinstance(entry.content, str):
            entry.content = wrap_text_in_tiptap_doc(entry.content)
            entry.save(update_fields=["content"])


class Migration(migrations.Migration):

    dependencies = [
        ("eln", "0002_alter_notebookentry_author"),
    ]

    operations = [
        # Step 1: convert existing text rows to valid JSON strings
        migrations.RunPython(convert_existing_content, migrations.RunPython.noop),
        # Step 2: alter the column type from text to jsonb
        migrations.AlterField(
            model_name="notebookentry",
            name="content",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
