# Generated by Django 5.1.15 on 2026-06-26 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('eln', '0005_generalize_mention_source_to_generic_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebookentry',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.folder'),
        ),
    ]
