# Generated by Django 5.1.15 on 2026-07-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helix_core', '0002_entity_hub_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityHubView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('display_id', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('properties', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('schema_type_id', models.CharField(max_length=50)),
                ('workspace_id', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'entity_hub_view',
                'ordering': ['-updated_at'],
                'managed': False,
            },
        ),
    ]
