# Generated by Django 5.1.15 on 2026-08-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helix_core', '0007_icon_library_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='color',
            field=models.CharField(blank=True, default='', help_text='Open key string referencing a ColorToken key. Soft reference with render-time fallback.', max_length=100),
        ),
        migrations.AddField(
            model_name='schema',
            name='icon',
            field=models.CharField(blank=True, default='', help_text='Open key string referencing an IconLibraryEntry key. Soft reference with render-time fallback.', max_length=100),
        ),
    ]
