# Generated by Django 5.1.15 on 2026-06-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0003_alter_entity_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitytype',
            name='icon',
            field=models.CharField(default='🧪', help_text='Single emoji used as the icon for this entity type in reference badges.', max_length=10),
        ),
    ]
