# Generated by Django 5.1.15 on 2026-07-23 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_project'),
        ('helix_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('items', models.JSONField(default=list, help_text="Ordered list of {type: 'step'|'note', text: string}")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'eln_protocol',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField()),
                ('content_hash', models.CharField(max_length=64)),
                ('version_number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('save_mode', models.CharField(choices=[('autosave', 'Autosave'), ('manual', 'Manual')], default='manual', max_length=10)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'eln_content_version',
                'ordering': ['entry', '-version_number'],
            },
        ),
        migrations.CreateModel(
            name='ElnAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=100)),
                ('target_type', models.CharField(help_text="Namespaced target type, e.g. 'eln.entry' or 'lims.entity'.", max_length=100)),
                ('target_id', models.IntegerField(help_text='PK of the target record.')),
                ('request_id', models.UUIDField(blank=True, help_text='Correlation ID tying together action rows from the same HTTP request.', null=True)),
                ('client_ip', models.GenericIPAddressField(blank=True, help_text='Client IP auto-captured from the request.', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actions', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(blank=True, help_text='Content version produced by this action. Null for non-versioned targets.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='eln.contentversion')),
            ],
            options={
                'db_table': 'eln_action',
            },
        ),
        migrations.CreateModel(
            name='EntryLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('held_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'eln_entry_lock',
            },
        ),
        migrations.CreateModel(
            name='NotebookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_id', models.CharField(editable=False, max_length=50, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('finished', 'Finished')], default='in_progress', max_length=20)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.folder')),
                ('last_editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, help_text='Placeholder FK — the Project model is not yet implemented.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.project')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='helix_core.schema')),
            ],
            options={
                'db_table': 'eln_entry',
                'ordering': ['-created_at'],
            },
        ),
    ]
