# Generated by Django 5.1.15 on 2026-07-16 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eln', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebookentry',
            name='tags',
            field=models.ManyToManyField(db_table='eln_tag_entries', related_name='+', to='tags.tag'),
        ),
        migrations.AddField(
            model_name='entrylock',
            name='entry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lock', to='eln.notebookentry'),
        ),
        migrations.AddField(
            model_name='contentversion',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_versions', to='eln.notebookentry'),
        ),
        migrations.AddConstraint(
            model_name='contentversion',
            constraint=models.UniqueConstraint(fields=('entry', 'version_number'), name='uq_entry_version'),
        ),
    ]
