# Generated by Django 5.1.15 on 2026-07-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eln', '0003_rename_action_type_to_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elnaction',
            name='action',
            field=models.CharField(help_text="Triple-dotted action identifier, e.g. 'eln.entry.created'.", max_length=128),
        ),
        migrations.AlterField(
            model_name='elnaction',
            name='action_type',
            field=models.CharField(help_text="Core CRUD verb: 'created', 'edited', or 'deleted'.", max_length=16),
        ),
    ]
