# Generated by Django 5.1.15 on 2026-07-30 08:29

from django.db import migrations, models

# The entity_hub_view VIEW selects from eln_entry and must be dropped before
# any ALTER COLUMN on its source tables, then recreated afterwards.
_VIEW_SQL = """
    CREATE VIEW entity_hub_view AS
    SELECT
        id, name, display_id, author_id, last_editor_id, status,
        folder_id, project_id, schema_id, properties, created_at, updated_at,
        'eln.notebookentry' AS schema_type_id,
        'eln' AS workspace_id
    FROM eln_entry
    UNION ALL
    SELECT
        id, name, display_id, author_id, last_editor_id, status,
        folder_id, project_id, schema_id, properties, created_at, updated_at,
        'lims.entity' AS schema_type_id,
        'lims' AS workspace_id
    FROM lims_entity;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("eln", "0004_alter_elnaction_action_alter_elnaction_action_type"),
        ("helix_core", "0004_fix_entity_hub_view_schema_type"),
        ("lims", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP VIEW IF EXISTS entity_hub_view;",
            reverse_sql="DROP VIEW IF EXISTS entity_hub_view;",
        ),
        migrations.AlterField(
            model_name="notebookentry",
            name="status",
            field=models.CharField(
                default="in_progress",
                help_text=(
                    "Status value from the dropdowns system. The canonical list of "
                    "valid statuses is stored in the Status dropdown (managed in "
                    "Settings → Dropdowns)."
                ),
                max_length=100,
            ),
        ),
        migrations.RunSQL(
            sql=_VIEW_SQL,
            reverse_sql=_VIEW_SQL,
        ),
    ]
