# Generated by Django 5.1.15 on 2026-08-27 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eln', '0008_source_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notebookentry',
            name='folder',
        ),
    ]
