# Generated by Django 5.1.15 on 2026-07-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eln', '0015_delete_mention'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('items', models.JSONField(default=list, help_text="Ordered list of {type: 'step'|'note', text: string}")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'eln_protocol',
                'ordering': ['-created_at'],
            },
        ),
    ]
