# Generated by Django 5.1.15 on 2026-07-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0004_add_entity_type_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('finished', 'Finished')], default='in_progress', max_length=20),
        ),
    ]
