# Generated by Django 5.1.15 on 2026-07-23 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eln', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(choices=[('enzyme', 'Enzyme'), ('flask', 'Flask'), ('solvent', 'Solvent'), ('warn', 'Warn'), ('primary', 'Primary'), ('success', 'Success'), ('destructive', 'Destructive'), ('muted', 'Muted')], default='muted', max_length=50)),
                ('icon', models.CharField(choices=[('circle', 'Circle'), ('dna', 'DNA'), ('rat', 'Rat'), ('leaf', 'Leaf'), ('cog', 'Machine'), ('notebook', 'Entry'), ('user', 'Person'), ('folder', 'Folder')], default='circle', max_length=50)),
            ],
            options={
                'db_table': 'tags_tag',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TagsAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=100)),
                ('target_type', models.CharField(help_text="Namespaced target type, e.g. 'eln.entry' or 'lims.entity'.", max_length=100)),
                ('target_id', models.IntegerField(help_text='PK of the target record.')),
                ('request_id', models.UUIDField(blank=True, help_text='Correlation ID tying together action rows from the same HTTP request.', null=True)),
                ('client_ip', models.GenericIPAddressField(blank=True, help_text='Client IP auto-captured from the request.', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actions', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(blank=True, help_text='Content version produced by this action. Null for non-versioned targets.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='eln.contentversion')),
            ],
            options={
                'verbose_name': 'Tags action',
                'verbose_name_plural': 'Tags actions',
                'db_table': 'tags_action',
            },
        ),
    ]
