# Generated by Django 5.1.15 on 2026-07-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
