# Generated by Django 5.1.15 on 2026-07-03 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_allow_blank_pin_label"),
        ("pins", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="PinnedWorkspace",
                ),
            ],
            database_operations=[],
        ),
    ]
