# Generated by Django 5.1.15 on 2026-08-02 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lims', '0007_metric_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surface', models.CharField(default='home', help_text='Surface key this card appears on (e.g. home, profile).', max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within the surface (lower = first).')),
                ('label', models.CharField(blank=True, max_length=255)),
                ('icon', models.CharField(default='flask-conical', help_text='Lucide icon token.', max_length=100)),
                ('formatting', models.JSONField(blank=True, default=dict, help_text='Conditional-formatting rules + default style.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='lims.metric')),
                ('owner', models.ForeignKey(blank=True, help_text='Null for global/system-owned cards shown to everyone.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'home_card',
                'ordering': ['surface', 'order'],
            },
        ),
    ]
