# Generated by Django 5.1.15 on 2026-07-16 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods_users', '0001_initial'),
        ('eln', '0017_elnaction_client_ip_elnaction_request_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coreaction',
            name='client_ip',
            field=models.GenericIPAddressField(blank=True, help_text='Client IP auto-captured from the request.', null=True),
        ),
        migrations.AddField(
            model_name='coreaction',
            name='request_id',
            field=models.UUIDField(blank=True, help_text='Correlation ID tying together action rows from the same HTTP request.', null=True),
        ),
        migrations.AddField(
            model_name='coreaction',
            name='version',
            field=models.ForeignKey(blank=True, help_text='Content version produced by this action. Null for non-versioned targets.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='eln.contentversion'),
        ),
        migrations.AlterField(
            model_name='coreaction',
            name='action_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coreaction',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actions', to=settings.AUTH_USER_MODEL),
        ),
    ]
