# Generated by Django 5.1.15 on 2026-07-16 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_mods_users', '0001_initial'),
        ('eln', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreaction',
            name='version',
            field=models.ForeignKey(blank=True, help_text='Content version produced by this action. Null for non-versioned targets.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='eln.contentversion'),
        ),
    ]
