# Generated by Django 5.1.15 on 2026-07-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pinnedworkspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinnedworkspace',
            name='label',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
