# Generated by Django 5.1.15 on 2026-07-05 11:34

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_pinnedworkspace'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'core_setting',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='color',
            field=models.CharField(default=core.models.random_user_color, max_length=7),
        ),
    ]
