# Generated by Django 5.1.15 on 2026-07-09 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eln', '0012_move_tag_to_tags_app'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField()),
                ('content_hash', models.CharField(max_length=64)),
                ('version_number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('save_mode', models.CharField(choices=[('autosave', 'Autosave'), ('manual', 'Manual')], default='manual', max_length=10)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_versions', to='eln.notebookentry')),
            ],
            options={
                'db_table': 'eln_content_version',
                'ordering': ['entry', '-version_number'],
                'constraints': [models.UniqueConstraint(fields=('entry', 'version_number'), name='uq_entry_version')],
            },
        ),
    ]
