# Generated by Django 5.1.15 on 2026-07-09 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eln', '0014_add_entry_lock'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(
                    name='Mention',
                ),
            ],
        ),
    ]
